name: Label PR as hacktoberfest-accepted on approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  label:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: hacktoberfest-accepted
